services:
  # mongodb: 
  #   image: "mongo"
  #   volumes:
  #     - url-shortener-db:/data/db
    
  #   env_file:
  #     - .env

  # url-shortener-server:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
    
  #   ports:
  #     - "4000:4000"
    
  #   volumes: 
  #     - .:/app 
  #     - /app/node_modules

  #   env_file:
  #     - .env

  #   depends_on:
  #     - mongodb

  prom-server:
    image: prom/prometheus
    container_name: prom-server
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml

volumes:
  # url-shortener-db:
  # url-shortener-server:
  prom-server:
